### PR TITLE
Support symbol properties

### PR DESCRIPTION
**Pull request by robinpokorny**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Support also symbol properties, like `Symbol.iterator`.

**Which issue (if any) does this pull request address?**
An inconsistency with how the spread operator works:

```ts
const tag = Symbol.for("tag");
const version = Symbol.for("version");
const createdAt = Symbol.for("createdAt");

const defaults = {
  [tag]: "user",
  [createdAt]: Date.UTC(2020, 1, 1),
};

Object.defineProperty(defaults, version, { value: 1, enumerable: false });

const object = {
  [createdAt]: Date.UTC(2023, 6, 1),
};

({ ...defaults, ...object })
// -> { [tag]: "user",  [createdAt]: Date.UTC(2023, 6, 1) };

defaultComposer<any>(defaults, object))
// -> {}
```

**Is there anything you'd like reviewers to focus on?**
1. The spread operator only considers enumerable properties, so a check for that had to be added.
2. Non-enumerable symbols on object that are enumerable on defaults will be applied. This can be fixed when #9 is merged by checking enumerable status for symbol properties in the function `hasOwn`.

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
Thanks for the contribution @robinpokorny ! LGTM!

**Comment by aralroca** [comment]
@robinpokorny There is a small error on the build process related with the types

**Comment by robinpokorny** [comment]
Rebased and fixed the type. Should I also change the `hasOwn` to filter out non-enumerable symbols in this PR?

**Comment by aralroca** [comment]
> Rebased and fixed the type. Should I also change the `hasOwn` to filter out non-enumerable symbols in this PR?

 Make sense to me. Thank you for your contribution 😊

**Comment by aralroca** [comment]
@robinpokorny I already did the release, now these changes are available under [0.4.0](https://github.com/aralroca/default-composer/releases/tag/0.4.0) version

**Pull request merged**
